/**
 * ai-generate.spec.ts — Lyricist Pro / Vibe
 * Full E2E coverage for AI generation providers: Gemini, Lyria, Suno.
 * ALL external API calls are mocked — no real keys required.
 */
import { test, expect, Page } from '@playwright/test';

// ---- mock factories ---------------------------------------------------------

function setupGeminiMock(page: Page, opts?: { error?: boolean }) {
  return page.route('**/api/ai/generate**', async (route) => {
    if (opts?.error) {
      await route.fulfill({ status: 500, body: JSON.stringify({ error: 'Gemini error (mocked)' }) });
    } else {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          lyrics: '[Verse 1]\nGenerated by Gemini\n[Chorus]\nAI-powered lyrics here',
          model: 'gemini-2.5-pro',
          provider: 'gemini',
        }),
      });
    }
  });
}

function setupLyriaMock(page: Page, opts?: { error?: boolean }) {
  return page.route('**/api/lyria/generate**', async (route) => {
    if (opts?.error) {
      await route.fulfill({ status: 502, body: JSON.stringify({ error: 'Lyria error (mocked)' }) });
    } else {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          audioUrl: 'https://example.com/lyria-mock.mp3',
          duration: 30,
          provider: 'lyria',
        }),
      });
    }
  });
}

function setupSunoMock(page: Page, opts?: { error?: boolean }) {
  return page.route('**/api/suno/generate**', async (route) => {
    if (opts?.error) {
      await route.fulfill({ status: 503, body: JSON.stringify({ error: 'Suno unavailable (mocked)' }) });
    } else {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({
          audioUrl: 'https://example.com/suno-mock.mp3',
          status: 'complete',
          provider: 'suno',
        }),
      });
    }
  });
}

// ---- helpers ----------------------------------------------------------------

async function fillLyricsAndOpenAI(page: Page, lyrics = 'Test song about the sea') {
  await page.goto('/');
  await page.waitForLoadState('networkidle');
  const editor = page
    .locator('[data-testid="lyrics-editor"], textarea, [contenteditable="true"]')
    .first();
  await editor.click();
  await editor.fill(lyrics);
}

// ---- tests ------------------------------------------------------------------

test.describe('AI Generate — Gemini (mocked)', () => {
  test('generate button triggers Gemini API and displays lyrics', async ({ page }) => {
    await setupGeminiMock(page);
    await fillLyricsAndOpenAI(page);

    const generateBtn = page
      .locator('button')
      .filter({ hasText: /generat|AI|créer|write/i })
      .first();
    await expect(generateBtn).toBeVisible();
    await generateBtn.click();

    await expect(page.locator('text=Generated by Gemini')).toBeVisible({ timeout: 10_000 });
  });

  test('Gemini API error shows user-facing error message (no crash)', async ({ page }) => {
    await setupGeminiMock(page, { error: true });
    const pageErrors: string[] = [];
    page.on('pageerror', (e) => pageErrors.push(e.message));

    await fillLyricsAndOpenAI(page);
    const generateBtn = page.locator('button').filter({ hasText: /generat|AI/i }).first();
    if (await generateBtn.isVisible()) {
      await generateBtn.click();
      await page.waitForTimeout(2000);
      // Should show an error UI, not throw
      expect(pageErrors).toHaveLength(0);
      // An error message should appear somewhere
      const errorEl = page.locator('[class*="error"], [role="alert"], text=/erreur|error|failed/i').first();
      if (await errorEl.isVisible()) {
        await expect(errorEl).toBeVisible();
      }
    } else {
      test.skip();
    }
  });

  test('provider selector can switch to OpenAI (if present)', async ({ page }) => {
    await page.route('**/api/ai/generate**', async (route) => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify({ lyrics: 'OpenAI generated lyrics', provider: 'openai' }),
      });
    });

    await page.goto('/');
    const providerSelect = page
      .locator('select, [data-testid="provider-select"], [aria-label*="provider" i]')
      .first();
    if (await providerSelect.isVisible()) {
      await providerSelect.selectOption({ label: /openai/i });
      await page.waitForTimeout(500);
      await expect(page).not.toHaveURL(/error/);
    } else {
      test.skip();
    }
  });
});

test.describe('AI Generate — Lyria music generation (mocked)', () => {
  test('Lyria generate returns audio URL and renders audio player', async ({ page }) => {
    await setupLyriaMock(page);
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    // Find a music / Lyria generate button
    const musicBtn = page
      .locator('button')
      .filter({ hasText: /lyria|music|mélodie|audio|generat.*music/i })
      .first();
    if (await musicBtn.isVisible()) {
      await musicBtn.click();
      // Look for an audio element or audio URL display
      const audio = page.locator('audio, [data-testid="audio-player"], a[href*=".mp3"]').first();
      await expect(audio).toBeVisible({ timeout: 10_000 });
    } else {
      test.skip();
    }
  });

  test('Lyria API error does not crash the app', async ({ page }) => {
    await setupLyriaMock(page, { error: true });
    const pageErrors: string[] = [];
    page.on('pageerror', (e) => pageErrors.push(e.message));

    await page.goto('/');
    const musicBtn = page.locator('button').filter({ hasText: /lyria|music|audio/i }).first();
    if (await musicBtn.isVisible()) {
      await musicBtn.click();
      await page.waitForTimeout(2000);
      expect(pageErrors).toHaveLength(0);
    } else {
      test.skip();
    }
  });
});

test.describe('AI Generate — Suno music generation (mocked)', () => {
  test('Suno generate returns audio and renders player', async ({ page }) => {
    await setupSunoMock(page);
    await page.goto('/');
    await page.waitForLoadState('networkidle');

    const sunoBtn = page
      .locator('button')
      .filter({ hasText: /suno|generat.*song|create.*song/i })
      .first();
    if (await sunoBtn.isVisible()) {
      await sunoBtn.click();
      const audio = page.locator('audio, [data-testid="audio-player"], a[href*=".mp3"]').first();
      await expect(audio).toBeVisible({ timeout: 10_000 });
    } else {
      test.skip();
    }
  });

  test('Suno error is handled gracefully', async ({ page }) => {
    await setupSunoMock(page, { error: true });
    const pageErrors: string[] = [];
    page.on('pageerror', (e) => pageErrors.push(e.message));

    await page.goto('/');
    const sunoBtn = page.locator('button').filter({ hasText: /suno/i }).first();
    if (await sunoBtn.isVisible()) {
      await sunoBtn.click();
      await page.waitForTimeout(2000);
      expect(pageErrors).toHaveLength(0);
    } else {
      test.skip();
    }
  });
});
