import type { RefObject } from 'react';
import type { AppTab } from '../hooks/useUIState';

export interface UIStateSlice {
  setIsAboutOpen: (v: boolean) => void;
  setIsSettingsOpen: (v: boolean) => void;
  setApiErrorModal: (v: { open: boolean; message: string }) => void;
  setIsExportModalOpen: (v: boolean) => void;
  setIsSectionDropdownOpen: (v: boolean) => void;
  setIsSimilarityModalOpen: (v: boolean) => void;
  setIsSaveToLibraryModalOpen: (v: boolean) => void;
  setIsVersionsModalOpen: (v: boolean) => void;
  setIsResetModalOpen: (v: boolean) => void;
  setIsKeyboardShortcutsModalOpen: (v: boolean) => void;
  setConfirmModal: (v: { open: boolean; onConfirm: () => void } | null) => void;
  setPromptModal: (v: { open: boolean; onConfirm: (value: string) => void } | null) => void;
  setIsPasteModalOpen: (v: boolean) => void;
  setIsAnalysisModalOpen: (v: boolean) => void;
  setIsSearchReplaceOpen: (v: boolean) => void;
  setIsAnalysisPanelOpen: (v: boolean) => void;
  setIsCloudStoragePickerOpen: (v: boolean) => void;
  isAboutOpen: boolean;
  isSettingsOpen: boolean;
  apiErrorModal: { open: boolean; message: string };
  isExportModalOpen: boolean;
  isSectionDropdownOpen: boolean;
  isSimilarityModalOpen: boolean;
  isSaveToLibraryModalOpen: boolean;
  isVersionsModalOpen: boolean;
  isResetModalOpen: boolean;
  isKeyboardShortcutsModalOpen: boolean;
  confirmModal: { open: boolean; onConfirm: () => void } | null;
  promptModal: { open: boolean; onConfirm: (value: string) => void } | null;
  isPasteModalOpen: boolean;
  isAnalysisModalOpen: boolean;
  isSearchReplaceOpen: boolean;
  isAnalysisPanelOpen: boolean;
  isCloudStoragePickerOpen: boolean;
  activeTab: AppTab;
  setActiveTab: (v: AppTab) => void;
  isStructureOpen: boolean;
  setIsStructureOpen: (v: boolean) => void;
  isLeftPanelOpen: boolean;
  setIsLeftPanelOpen: (v: boolean) => void;
  importInputRef: RefObject<HTMLInputElement>;
}
